import { tr } from '../translations';
import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { api, type Meeting } from '../api';
import type { Labels } from '../i18n';

export function Meetings({t,open,canCreate}: {canCreate:boolean;t:Labels;open:(id:string)=>void}) {
 const [creating,setCreating]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const query=useQuery({queryKey:['meetings'],queryFn:()=>api<Meeting[]>('/meetings')});
 const cache=useQueryClient();
 async function create(e:React.FormEvent<HTMLFormElement>) {e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try {const m=await api<Meeting>('/meetings','POST',{title:f.get('title'),date:f.get('date')||null,language:f.get('language'),timezone:f.get('timezone'),classification:f.get('classification'),participants:String(f.get('participants')).split('\n').filter(Boolean)});await cache.invalidateQueries({queryKey:['meetings']});open(m.id);}catch(e){setError(e instanceof Error ? e.message : tr('The request failed. Check the form, refresh, and try again.'));}finally{setBusy(false);}}
 return <><div className="pageheading"><div><p className="eyebrow">{tr("YOUR MEETING RECORD")}</p><h1>{t.meetings}</h1><p>{tr("From conversation to reviewed decisions.")}</p></div>{canCreate&&<button onClick={()=>setCreating(!creating)}>＋ {t.new}</button>}</div>
 {error&&<p role="alert" className="error">{error}</p>}
 {creating&&<form className="card form" onSubmit={create}><h2>{t.new}</h2><label>{t.title}<input name="title" required maxLength={200} autoFocus/></label><div className="formrow"><label>{t.date}<input name="date" type="date" defaultValue=""/></label><label>{tr("Timezone")}<input name="timezone" defaultValue=""/></label></div><p className="caption">{tr("Leave date and timezone blank if unknown. Relative dates will need review.")}</p><div className="formrow"><label>{tr("Minutes language")}<select name="language"><option value="en">English</option><option value="ro">Română</option><option value="ru">Русский</option></select></label><label>{tr("Classification")}<select name="classification"><option value="Administrative">{tr("Administrative")}</option><option value="Executive">{tr("Executive")}</option><option value="Medical">{tr("Medical")}</option></select></label></div><label>{t.participants}<textarea name="participants" rows={3}/></label><button disabled={busy}>{busy?t.loading:t.save}</button></form>}
 {query.isPending?<p role="status">{t.loading}</p>:query.isError?<p role="alert">{String(query.error)}</p>:query.data.length===0?<section className="card empty"><span className="emptyicon">▤</span><h2>{canCreate?t.empty:tr("No meetings have been shared with you yet.")}</h2>{canCreate&&<><p>{tr("Create a meeting, add your participants, then record or upload audio.")}<br/>{tr("Every decision stays connected to its source.")}</p><button onClick={()=>setCreating(true)}>{t.new}</button></>}</section>:<div className="meetinglist">{query.data.map(m=><button className="meetingrow" key={m.id} onClick={()=>open(m.id)}><span className="datebox">{m.date?m.date.slice(8):"—"}<small>{m.date?m.date.slice(0,7):tr("Date unknown")}</small></span><span><strong>{m.title}</strong><small>{tr(m.classification)} · {m.language.toUpperCase()}</small></span><span className="badge">{tr(m.status.replaceAll('_',' '))}</span><span aria-hidden>→</span></button>)}</div>}
 <div className="guidance"><h3>{tr("A record you can trace")}</h3><p>{tr("Review the original speech, see where a decision changed, and approve an exact version before sending.")}</p></div></>;
}
