import { useEffect, useRef, useState } from 'react';
import { api } from '../api';
import type { Labels } from '../i18n';

export function Recorder({meeting,t,done}: {meeting:string;t:Labels;done:()=>void}) {
 const [state,setState]=useState<'idle'|'recording'|'paused'|'saving'|'error'>('idle'),[saved,setSaved]=useState(0),[error,setError]=useState('');
 const control=useRef<{ctx:AudioContext;stream:MediaStream;node:AudioWorkletNode;id:string;sequence:number;pending:Promise<void>;backlog:number;gaps:any[];pausedAt?:number}|undefined>(undefined);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(control.current){e.preventDefault();e.returnValue='Unsaved recording may be lost';}};window.addEventListener('beforeunload',warn);return()=>{window.removeEventListener('beforeunload',warn);control.current?.stream.getTracks().forEach(t=>t.stop());void control.current?.ctx.close();};},[]);
 async function start(){try {setError('');const stream=await navigator.mediaDevices.getUserMedia({audio:true});const ctx=new AudioContext();await ctx.audioWorklet.addModule('/pcm-worklet.js');const r=await api<{id:string}>(`/meetings/${meeting}/recordings`,'POST',{sample_rate:ctx.sampleRate});const node=new AudioWorkletNode(ctx,'pcm-capture');const c={ctx,stream,node,id:r.id,sequence:0,pending:Promise.resolve(),backlog:0,gaps:[]};control.current=c;
 node.port.onmessage=e=>{const sequence=c.sequence++;const pcm=e.data as ArrayBuffer;c.backlog+=pcm.byteLength/2;if(c.backlog>ctx.sampleRate*60){stream.getTracks().forEach(t=>t.stop());setState('error');setError('Saving backlog exceeded 60 seconds. Acknowledged audio is retained.');return;}c.pending=c.pending.then(async()=>{const result=await api<any>(`/recordings/${c.id}/chunks/${sequence}`,'PUT',pcm);c.backlog-=pcm.byteLength/2;setSaved(result.acknowledged_samples/result.sample_rate);}).catch(e=>{setError(String(e));setState('error');stream.getTracks().forEach(t=>t.stop());throw e;});};
 stream.getTracks().forEach(track=>track.onended=()=>{setError('Microphone disconnected. Saved audio remains available.');setState('error');});ctx.createMediaStreamSource(stream).connect(node);const mute=ctx.createGain();mute.gain.value=0;node.connect(mute).connect(ctx.destination);setState('recording');}catch(e){setError(String(e));setState('error');}}
 async function stop(){const c=control.current;if(!c)return;setState('saving');c.node.port.postMessage('flush');await new Promise(r=>setTimeout(r,150));c.stream.getTracks().forEach(t=>{t.onended=null;t.stop();});try{await c.pending;await api(`/recordings/${c.id}/finish`,'POST',{count:c.sequence,gaps:c.gaps});await c.ctx.close();control.current=undefined;setState('idle');done();}catch(e){setState('error');setError(String(e));}}
 function pause(){const c=control.current;if(!c)return;if(state==='paused'){c.gaps.push({after_sequence:c.sequence-1,wall_duration_ms:Date.now()-(c.pausedAt||Date.now())});c.node.port.postMessage('resume');setState('recording');}else{c.pausedAt=Date.now();c.node.port.postMessage('flush');c.node.port.postMessage('pause');setState('paused');}}
 return <section className="capture"><div><strong>{t.saved}: {saved.toFixed(1)} s</strong><p>Audio is acknowledged only after local storage succeeds.</p></div>{state==='idle'?<button className="secondary" onClick={start}>{t.record}</button>:<><span role="status">{state}</span><button className="secondary" onClick={pause} disabled={state==='saving'}>{state==='paused'?t.resume:t.pause}</button><button onClick={stop} disabled={state==='saving'}>{t.stop}</button></>}{error&&<p role="alert" className="error">{error}</p>}</section>;
}
