import { tr } from '../translations';
import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { api } from '../api';

export function Settings({role}:{role:string}){
 const q=useQuery({queryKey:['proof'],queryFn:()=>api('/system/proof')}),groups=useQuery({queryKey:['groups'],queryFn:()=>api<any[]>('/recipient-groups')}),glossary=useQuery({queryKey:['glossary'],queryFn:()=>api('/settings/glossary'),enabled:role==='admin'});
 const [status,setStatus]=useState(''),[busy,setBusy]=useState(false);const cache=useQueryClient();
 async function save(fn:()=>Promise<unknown>){setBusy(true);setStatus('');try{await fn();await cache.invalidateQueries();setStatus(tr('Saved on this computer.'));}catch(e){setStatus(e instanceof Error ? e.message : tr('The request failed. Check the form, refresh, and try again.'));}finally{setBusy(false);}}
 return <><p className="eyebrow">{tr("WORKSPACE SETTINGS")}</p><h1>{tr("Settings")}</h1>{status&&<p role="status" className="notice">{status}</p>}<section className="card"><h2>{tr("Local processing")}</h2><p>{tr("Inference runs locally. Network monitoring: ")}<strong>{tr(q.data?.network_observation||'Not measured')}</strong></p><p>{tr("Model files present: ")}{JSON.stringify(q.data?.models||{})}</p><h3>{tr("Optional capabilities")}</h3>{Object.entries(q.data?.capabilities||{}).map(([name,v])=>{const c=v as any;return <p key={name}><strong>{tr(name)}</strong> — {tr(c.available?'Available':'Unavailable')} · {tr(c.qualification)}<br/>{c.prerequisite&&tr(c.prerequisite)}</p>;})}<p className="notice">{tr("Romanian and Russian translations need native review. Target 8 GB laptop qualification remains separate from this host.")}</p><a href="http://127.0.0.1:8025" target="_blank" rel="noreferrer">{tr("Open local Mailpit inbox ↗")}</a></section>
 <section className="card"><h2>{tr("Allowed recipient groups")}</h2>{groups.data?.map(g=><article key={g.id}><p>{g.name}{tr(" · version ")}{g.version}: {g.addresses.join(', ')}</p>{role==='admin'&&<GroupEditor group={g} busy={busy} save={save}/>}</article>)}{role==='admin'&&<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void save(()=>api('/recipient-groups','POST',{name:f.get('name'),addresses:String(f.get('addresses')).split('\n').filter(Boolean)}));}}><label>{tr("New group name")}<input name="name" required/></label><label>{tr("Addresses, one per line")}<textarea name="addresses" required placeholder="secretary@secure-mom.test"/></label><p className="caption">{tr("Admin only. Domains must match the operator's configured allowlist. A model cannot add recipients.")}</p><button disabled={busy}>{tr("Save recipient group")}</button></form>}</section>
 <section className="card"><h2>{tr("Glossary candidates")}</h2>{glossary.data?<form key={glossary.data.version} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void save(()=>api('/settings/glossary','PUT',{version:glossary.data.version,terms:String(f.get('terms')).split('\n').filter(Boolean)}));}}><label>{tr("Terms, one per line")}<textarea name="terms" defaultValue={glossary.data.terms.join('\n')} rows={5}/></label><p className="caption">{tr("Reference candidates only. Unknown names are never automatically replaced.")}</p><button disabled={busy}>{tr("Save glossary")}</button></form>:<p>{tr("Admin access required to edit glossary.")}</p>}</section>
 {role==='admin'&&<section className="card"><h2>{tr("Create local account")}</h2><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void save(()=>api('/accounts','POST',{name:f.get('name'),password:f.get('password'),role:f.get('role')}));}}><label>{tr("Username")}<input name="name" required minLength={3}/></label><label>{tr("Password")}<input name="password" type="password" required minLength={12} autoComplete="new-password"/></label><label>{tr("Role")}<select name="role" aria-label={tr("Role")}><option value="secretary">{tr("secretary")}</option><option value="viewer">{tr("viewer")}</option><option value="admin">{tr("admin")}</option></select></label><p className="caption">{tr("Admin role does not grant access to other people's meetings.")}</p><button disabled={busy}>{tr("Create account")}</button></form></section>}</>;
}

function GroupEditor({group:g,busy,save}:{group:any;busy:boolean;save:(fn:()=>Promise<unknown>)=>void}) {
 return <details><summary>{tr('Edit recipient group')}: {g.name}</summary><form key={g.version} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);save(()=>api('/recipient-groups','POST',{id:g.id,version:g.version,name:f.get('edit_name'),addresses:String(f.get('edit_addresses')).split('\n').map(s=>s.trim()).filter(Boolean)}));}}><label>{tr('Group name')}<input name="edit_name" defaultValue={g.name} required/></label><label>{tr('Updated addresses, one per line')}<textarea name="edit_addresses" aria-label={tr('Updated addresses, one per line')} defaultValue={g.addresses.join('\n')} required/></label><p className="caption">{tr('Changes apply to new deliveries. Previously queued deliveries keep their original recipients.')}</p><button disabled={busy}>{tr('Save group changes')}</button></form></details>;
}
