import { errorMessage } from '../errors';
import { tr } from '../translations';
import { useCallback, useMemo, useState } from 'react';
import { Settings2, ChevronDown } from 'lucide-react';
import { MeetingAudio, useMeetingAudio } from './MeetingAudio';
import { TranscriptExperience, loadTranscript } from './TranscriptExperience';
import { activeSegment, speakerIndex, speakerPalette, timeLabel, type SpeechSegment } from './transcriptModel';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { api, type Meeting } from '../api';
import type { Labels } from '../i18n';
import { Recorder } from './Recorder';
import { JobProgress } from './JobProgress';
import { AudioChecks } from './AudioChecks';
import { MeetingDetails, CandidateHistory } from './MeetingDetails';

export function Workspace({id,t,back,role}: {id:string;t:Labels;back:()=>void;role:string}) {
 const [tab,setTab]=useState('transcript'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[selection,setSelection]=useState<any>(null),[field,setField]=useState('text');
 const [toolsOpen,setToolsOpen]=useState(false),[category,setCategory]=useState('all'),[jumpId,setJumpId]=useState<string>();
 const [profile,setProfile]=useState({device:'cuda',parakeet:false,diarization:false});
 const capabilities=useQuery({queryKey:['proof'],queryFn:()=>api('/system/proof')});
 const cache=useQueryClient();
 const meeting=useQuery({queryKey:['meeting',id],queryFn:()=>api<Meeting>(`/meetings/${id}`),refetchInterval:2000});
 const review=useQuery({queryKey:['review',id],queryFn:()=>api<any>(`/meetings/${id}/items`),refetchInterval:4000});
 const transcript=useQuery({queryKey:['transcript-all',id,meeting.data?.revision],queryFn:({signal})=>loadTranscript(id,signal),refetchInterval:meeting.data?.jobs?.some(j=>['queued','running'].includes(j.state))?5000:false});
 const audio=useMeetingAudio(meeting.data?.assets);
 const segments=useMemo(()=>(transcript.data||[]).filter(s=>s.asset_id===audio.asset?.id),[transcript.data,audio.asset?.id]);
 const active=useMemo(()=>activeSegment(segments,audio.current),[segments,audio.current]);
 const seek=useCallback((s:SpeechSegment)=>audio.seek(s.start/16000,true,s.asset_id),[audio.seek]);
 const saveTranscript=useCallback(async(s:SpeechSegment,text:string,speaker:string|null)=>{setBusy(true);try{await api(`/segments/${s.id}/revisions`,'POST',{revision:s.revision,text,speaker});await cache.invalidateQueries();}finally{setBusy(false);}},[cache]);
 const snapshots=useQuery({queryKey:['snapshots',id],queryFn:()=>api<any[]>(`/meetings/${id}/snapshots`)});
 const groups=useQuery({queryKey:['groups'],queryFn:()=>api<any[]>('/recipient-groups')});
 const refresh=async()=>{await cache.invalidateQueries();};
 async function act(fn:()=>Promise<unknown>){setError('');setBusy(true);try{await fn();await refresh();}catch(e){setError(e instanceof Error ? e.message : tr('The request failed. Check the form, refresh, and try again.'));}finally{setBusy(false);}}
 async function upload(file:File){const form=new FormData();form.append('file',file);await act(()=>api(`/meetings/${id}/uploads`,'POST',form));}
 function play(segment:any){audio.seek(Math.max(0,segment.start/16000-2),true,segment.asset_id);}

 async function openTranscript(ref:any){try{const segment=await api<SpeechSegment>(`/segments/${ref.segment_id}`);setJumpId(segment.id);setTab('transcript');audio.seek(segment.start/16000,true,segment.asset_id);}catch(e){setError(String(e));}}
 async function playEvidence(ref:any){try{const segment=await api(`/segments/${ref.segment_id}`);play(segment);}catch(e){setError(e instanceof Error ? e.message : tr('The request failed. Check the form, refresh, and try again.'));}}

 if(meeting.isPending)return <p role="status">{t.loading}</p>;
 if(meeting.isError)return <p role="alert">{String(meeting.error)}</p>;
 const m=meeting.data,candidates=review.data?.candidates||[],visibleCandidates=candidates.filter((c:any)=>(category==='all'||c.body.category===category)&&(!search||`${c.body.subject} ${c.body.text}`.toLocaleLowerCase().includes(search.toLocaleLowerCase()))),selected=visibleCandidates.find((c:any)=>c.id===selection)||visibleCandidates[0];
 const latestJobs=new Map<string,NonNullable<Meeting['jobs']>[number]>();
 for(const job of m.jobs||[])if(!job.transcript_only&&job.created>=(latestJobs.get(job.asset_id)?.created??-1))latestJobs.set(job.asset_id,job);
 const refs=selected?.evidence?.filter((e:any)=>e.field===field)||[];
 return <section className="meeting-workspace"><div className="workspace-breadcrumb"><button className="textbutton" onClick={back}>← {t.back}</button><button className="workspace-options textbutton" onClick={()=>setToolsOpen(!toolsOpen)} aria-expanded={toolsOpen}><Settings2 size={16}/>{tr('Meeting options')}<ChevronDown size={14}/></button></div><div className="pageheading workspace-heading"><div><h1>{m.title}</h1><p>{m.date||tr('Date unknown')} {m.time} <span className="metadata-dot">·</span> {tr(m.classification)} <span className="metadata-dot">·</span> {tr('Local workspace')}</p></div></div>
 {error&&<p className="error" role="alert">{error}</p>}
 {toolsOpen&&<div className="workspace-tools">
 {m.notes&&<details className="card"><summary>{tr("Meeting notes · draft")}</summary><p style={{whiteSpace:"pre-wrap",lineHeight:1.7}}>{m.notes}</p></details>}
 <MeetingDetails meeting={m} role={role} busy={busy} act={act} back={back}/>
 <details className="card"><summary>{tr("Audio & processing")}</summary><fieldset className="mutation-controls" disabled={role==='viewer'}><div className="toolbar"><label>{tr("Inference device")}<select value={profile.device} onChange={e=>setProfile({...profile,device:e.target.value})}><option value="cuda">{tr("GPU")}</option><option value="cpu">{tr("CPU (explicit slower profile)")}</option></select></label>{(['parakeet','diarization'] as const).map(name=><label key={name}><span><input type="checkbox" checked={profile[name]} disabled={!capabilities.data?.capabilities?.[name]?.available} onChange={e=>setProfile({...profile,[name]:e.target.checked})}/>{tr(name)}</span><small>{tr(capabilities.data?.capabilities?.[name]?.available?'Available, not qualified':'Assets or dependencies not prepared')}</small></label>)}</div><div className="toolbar"><label className="filelabel">{t.upload}<input aria-label={t.upload} type="file" accept=".wav,.mp3,.m4a,.ogg,.flac,.webm" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);}}/></label>{m.assets?.map(a=><span key={a.id}>{(a.samples/a.sample_rate).toFixed(1)}{tr(" s saved ")}<button disabled={busy} onClick={()=>act(()=>api(`/meetings/${id}/jobs`,'POST',{asset_id:a.id,...profile}))}>{t.process}</button></span>)}</div>{m.recordings?.filter(r=>r.state==='recording'&&r.acknowledged_chunks>0).map(r=><div className="notice" key={r.id}><strong>{tr("Recover saved recording")}</strong><p>{(r.acknowledged_samples/r.rate).toFixed(1)}{tr(" seconds acknowledged. Unacknowledged audio from a closed browser cannot be recovered.")}</p><button disabled={busy} onClick={()=>act(()=>api(`/recordings/${r.id}/finish`,'POST',{count:r.acknowledged_chunks,gaps:[{reason:'Recovered after interruption; missing wall interval unknown'}]}))}>{tr("Seal acknowledged audio")}</button></div>)}<Recorder meeting={id} t={t} done={refresh}/>{m.jobs?.map(j=><div className="job" role="status" key={j.id}><strong>{tr(j.stage.replaceAll('_',' '))}</strong> · {tr(j.state)}<JobProgress job={j}/>{j.error&&<span className="error">{errorMessage(j.error)}{tr(" — source audio retained")}</span>}{['queued','running'].includes(j.state)?<button className="secondary" onClick={()=>act(()=>api(`/jobs/${j.id}/cancel`,'POST'))}>{tr("Cancel analysis")}</button>:['failed','cancelled'].includes(j.state)?<button onClick={()=>act(()=>api(`/jobs/${j.id}/retry`,'POST'))}>{tr("Retry")}</button>:null}</div>)}</fieldset></details>
 {!!m.transcript_pending_assets?.length&&<section className="notice"><p>{tr('The transcript changed. Reanalyze it before creating new minutes.')}</p>{m.transcript_pending_assets.map(asset=><button key={asset} disabled={busy||role==='viewer'||m.jobs?.some(j=>['queued','running'].includes(j.state))} onClick={()=>act(()=>api(`/meetings/${id}/jobs`,'POST',{asset_id:asset,device:profile.device,transcript_only:true}))}>{tr('Reanalyze corrected transcript')}</button>)}</section>}
 {Array.from(latestJobs.values()).map(j=><AudioChecks key={j.id} jobId={j.id} running={['queued','running'].includes(j.state)} play={play} revision={m.revision} readOnly={role==='viewer'} disabled={busy||m.jobs?.some(j=>['queued','running'].includes(j.state))}/>)}
 {role!=='viewer'&&!!m.assets?.length&&<details className="card"><summary>{tr("Import supplied transcript")}</summary><p>{tr("Upload timestamped speaker text. The original is preserved; audio verification remains separate.")}</p><form onSubmit={e=>{e.preventDefault();const form=new FormData(e.currentTarget),file=form.get('transcript') as File;void act(async()=>{await api(`/meetings/${id}/transcript-imports`,'POST',{asset_id:form.get('asset'),revision:m.revision,source:await file.text(),filename:file.name});});}}><label>{tr("Source audio")}<select name="asset">{m.assets?.map(a=><option key={a.id} value={a.id}>{(a.samples/a.sample_rate).toFixed(1)}s · {a.id.slice(0,8)}</option>)}</select></label><label>{tr("Transcript file")}<input name="transcript" type="file" accept=".txt" required/></label><button disabled={busy||m.jobs?.some(j=>['queued','running'].includes(j.state))}>{tr("Import supplied transcript")}</button></form></details>}
 </div>}
 <div className="tabs" role="tablist">{(['review','transcript','minutes'] as const).map(k=><button role="tab" aria-selected={tab===k} key={k} onClick={()=>setTab(k)}>{t[k]}</button>)}</div>
 <MeetingAudio state={audio} segments={segments}/>
 {m.assets&&m.assets.length>1&&<label className="asset-switch">{tr('Recording')}<select value={audio.asset?.id} onChange={e=>audio.seek(0,false,e.target.value)}>{m.assets.map((a,i)=><option key={a.id} value={a.id}>{tr('Recording')} {i+1} · {timeLabel(a.samples/a.sample_rate)}</option>)}</select></label>}
 <div className="recording-metadata"><div className="speaker-key" aria-label={tr("Speaker key")}>{Array.from(new Set(segments.map(s=>s.speaker).filter(Boolean))).map(name=><span key={name} style={{color:speakerPalette[speakerIndex(name)]}}><i style={{background:"currentColor"}}/>{name}</span>)}</div>{segments.some(s=>s.raw.includes('user_supplied_transcript'))&&<span>{tr('Imported transcript · approximate timestamps')}</span>}</div>
 {tab!=='transcript'&&!!m.transcript_pending_assets?.length&&<p className="notice">{tr('Transcript updated. Review affected items before approving minutes.')}</p>}
 {tab==='review'&&<div className="review-toolbar"><div className="category-filters">{['all','action','decision','information'].map(k=><button key={k} aria-pressed={category===k} onClick={()=>{setCategory(k);setSelection(null);}}>{tr(k==='all'?'All items':k)} <span>{candidates.filter((c:any)=>k==='all'||c.body.category===k).length}</span></button>)}</div><input aria-label={tr('Find an action or decision')} placeholder={tr('Find an action or decision')} value={search} onChange={e=>setSearch(e.target.value)}/></div>}
 {tab==='review'&&<div className="reviewgrid"><section className="card itemlist"><h2>{tr("Decisions & actions")}</h2><p className="caption">{candidates.filter((c:any)=>!['accepted','excluded'].includes(c.review)).length} {tr("to review")}</p>{!candidates.length&&<p>{tr("No extracted events yet. Process saved audio to begin.")}</p>}{visibleCandidates.map((c:any)=><button className={selected?.id===c.id?'selected':''} key={c.id} onClick={()=>{setSelection(c.id);setField('text');}}><strong>{c.body.subject}</strong><small>{tr(c.body.kind)} · {tr(c.review.replaceAll('_',' '))}</small></button>)}</section>
 <section className="card detail">{selected?<><p className="eyebrow">{tr(selected.body.category)} · {tr(selected.body.kind)}</p><h2>{selected.body.text}</h2><p className="badge">{tr("Review: ")}{tr(selected.review.replaceAll('_',' '))}</p>{(['owner','due','condition','value'] as const).map(f=><button className="field" key={f} onClick={()=>setField(f)}><span>{tr(f)}</span><strong>{selected.body[f]||t.notSpecified}</strong><small>{tr("View source ↗")}</small></button>)}{selected.body.uncertainties.length>0&&<p className="caption">{tr("Processing warning (original wording)")}</p>}{selected.body.uncertainties.map((u:string)=><p className="notice" key={u}>{u}</p>)}<div className="toolbar"><button disabled={busy||role==='viewer'||selected.review==='accepted'||!!m.transcript_pending_assets?.length||m.jobs?.some(j=>['queued','running'].includes(j.state))||review.data?.revision!==m.revision} onClick={()=>act(()=>api(`/review-issues/${selected.id}/resolve`,'POST',{revision:review.data.revision,action:'accepted'}))}>{t.accept}</button><button className="secondary" disabled={busy||role==='viewer'||selected.review==='excluded'} onClick={()=>act(()=>api(`/review-issues/${selected.id}/resolve`,'POST',{revision:review.data.revision,action:'excluded'}))}>{t.exclude}</button></div><p className="caption">{tr("Acceptance confirms your review of the interpretation, including each field.")}</p>{role!=='viewer'&&<CorrectionForm key={selected.id} candidate={selected} revision={review.data.revision} act={act} corrected={setSelection} subjects={[...new Set<string>(candidates.map((c:any)=>c.body.subject))]}/> }</>:<h2>{tr("Review the evidence before approving")}</h2>}</section>
 <aside className="card evidence"><p className="eyebrow">{tr("SOURCE EVIDENCE · ")}{tr(field)}</p>{refs.length?refs.map((r:any)=>{return <div key={r.id}><blockquote>{r.quote}</blockquote><p>{tr("Transcript revision ")}{r.revision}</p><button className="secondary" onClick={()=>playEvidence(r)}>{tr("▶ Play source clip")}</button><button className="textbutton source-jump" onClick={()=>void openTranscript(r)}>{tr("Open in transcript")} ↗</button></div>;}):<p>{tr("No source supplied for this field. Keep unsupported values unresolved.")}</p>}<CandidateHistory id={selected?.id}/></aside></div>}
 {tab==='transcript'&&(transcript.isPending?<p role="status">{t.loading}</p>:transcript.isError?<p role="alert" className="error">{String(transcript.error)}</p>:<TranscriptExperience jumpId={jumpId} segments={segments} activeId={audio.loaded?active?.id:undefined} readOnly={role==='viewer'} seek={seek} save={saveTranscript} busy={busy}/>)}
 {tab==='minutes'&&<section className="card"><div className="pageheading"><div><h2>{tr("Versioned minutes")}</h2><p>{tr("Resolve every review item, then create an immutable preview.")}</p></div><button disabled={busy||role==='viewer'} onClick={()=>act(()=>api(`/meetings/${id}/snapshots`,'POST',{revision:m.revision}))}>{tr("Create preview")}</button></div>{snapshots.data?.map(s=><Snapshot key={s.id} snapshot={s} revision={m.revision} t={t} groups={groups.data||[]} act={act} busy={busy||role==='viewer'}/>)}{!snapshots.data?.length&&<p>{tr("No versions yet. Approval and sending are separate steps.")}</p>}</section>}
 </section>;
}


function Snapshot({snapshot:s,revision,t,groups,act,busy}:{snapshot:any;revision:number;t:Labels;groups:any[];act:(fn:()=>Promise<unknown>)=>void;busy:boolean}) {
 const delivery=useQuery({queryKey:['delivery',s.id],queryFn:()=>api<any[]>(`/snapshots/${s.id}/deliveries`),refetchInterval:2000});
 const [groupId,setGroupId]=useState(''),[allowOlder,setAllowOlder]=useState(false);
 const group=groups.find(g=>g.id===groupId)||groups.find(g=>g.id===s.suggested_group_id)||groups[0],stale=s.revision!==revision;
 return <article className="snapshot"><h3>{tr("Revision ")}{s.revision} <span className="badge">{tr(s.approved?'Approved':'Draft')}{stale?' · '+tr('Older version'):''}</span></h3><details className="version-details"><summary>{tr("Version details")}</summary><p>{tr("Template version")}: {s.template_revision??0}</p><p className="hash">SHA-256 {s.hash}</p></details><div className="toolbar">{['html','pdf','json'].map(f=><a key={f} target="_blank" rel="noreferrer" href={`/api/v1/snapshots/${s.id}/exports/${f}`}>{f.toUpperCase()} ↗</a>)}</div><details className="delivery-options"><summary>{tr("Approval & delivery")}</summary><label>{tr("Recipient group")}<select aria-label={tr("Recipient group")} value={group?.id||''} onChange={e=>setGroupId(e.target.value)}>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label><p>{tr("Allowed recipients: ")}<strong>{group?.addresses.join(', ')||tr('No group configured')}</strong>{tr(" · group version ")}{group?.version}</p><div className="toolbar"><button disabled={busy||!!s.approved||stale} onClick={()=>act(()=>api(`/snapshots/${s.id}/approve`,'POST',{revision}))}>{t.approve}</button><button disabled={busy||!s.approved||(stale&&!allowOlder)||!group} onClick={()=>act(()=>api(`/snapshots/${s.id}/deliveries`,'POST',{group_id:group.id,group_version:group.version,explicitly_send_older:stale&&allowOlder}))}>{stale?tr("Send this older approved version"):t.send}</button></div>{stale&&s.approved&&<label><input type="checkbox" checked={allowOlder} onChange={e=>setAllowOlder(e.target.checked)}/>{tr("I choose this older approved version and the recipients shown above.")}</label>}{stale&&<p className="notice">{tr("This version is retained for history. Create a current preview to send.")}</p>}{delivery.data?.map(d=><div key={d.id}><p role="status">{tr("Local delivery: ")}{tr(d.state.replaceAll('_',' '))} {d.error?errorMessage(d.error):''}</p><p className="caption">{tr("Recipients for this delivery")}: {JSON.parse(d.addresses).join(', ')}</p>{d.state==='failed'&&<button disabled={busy||(stale&&!allowOlder)} onClick={()=>act(()=>api(`/deliveries/${d.id}/retry`,'POST',{explicitly_send_older:stale&&allowOlder}))}>{tr('Retry this failed delivery')}</button>}{d.state==='uncertain'&&<p className="notice">{tr('Delivery is uncertain. Check the mail server; this attempt cannot be retried automatically.')}</p>}</div>)}</details></article>;
}

function CorrectionForm({candidate,revision,act,corrected,subjects}:{candidate:any;revision:number;act:(fn:()=>Promise<unknown>)=>void;corrected:(id:string)=>void;subjects:string[]}) {
 return <details><summary>{tr("Secretary amendment")}</summary><p className="notice">{tr("Changes are labeled as reviewer additions. No audio evidence is invented for edited fields.")}</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);act(async()=>{const result=await api(`/items/${candidate.id}/corrections`,'POST',{revision,subject:f.get('subject'),text:f.get('text'),owner:f.get('owner')||null,due:f.get('due')||null,condition:f.get('condition')||null,value:f.get('value')||null,resolved_issues:f.getAll('resolved_issues'),reason:f.get('reason'),category:f.get('category'),kind:f.get('kind')});corrected(result.id);});}}><label>{tr("Topic / item key")}<input name="subject" list="known-topics" defaultValue={candidate.body.subject} required maxLength={160}/></label><datalist id="known-topics">{subjects.map(subject=><option key={subject} value={subject}/>)}</datalist><p className="caption">{tr("Use the same key only for the same task and scope. A new key separates unrelated items. Explain the link or split below.")}</p><label>{tr("Text")}<textarea name="text" aria-label={tr("Text")} defaultValue={candidate.body.text} required/></label><label>{tr("Owner")}<input name="owner" defaultValue={candidate.body.owner||''}/></label><label>{tr("Due")}<input name="due" type="date" defaultValue={candidate.body.due||''}/></label><label>{tr("Condition")}<textarea name="condition" aria-label={tr("Condition")} defaultValue={candidate.body.condition||''}/></label><label>{tr("Value")}<input name="value" defaultValue={candidate.body.value||''}/></label><label>{tr("Category")}<select name="category" defaultValue={candidate.body.category}>{['action','decision','information'].map(v=><option key={v} value={v}>{tr(v)}</option>)}</select></label><label>{tr("Speech act")}<select name="kind" defaultValue={candidate.body.kind}>{['propose','confirm','amend','reject','cancel','reopen','inform'].map(v=><option key={v} value={v}>{tr(v)}</option>)}</select></label>{candidate.body.uncertainties.length>0&&<fieldset><legend>{tr("Issues I have resolved")}</legend><p className="caption">{tr("Only check an issue after reviewing its source. Your reason is retained in the amendment history.")}</p>{candidate.body.uncertainties.map((issue:string)=><label key={issue}><input type="checkbox" name="resolved_issues" value={issue}/>{issue}</label>)}</fieldset>}<label>{tr("Reason for amendment")}<input name="reason" required minLength={3}/></label><button>{tr("Save reviewed amendment")}</button></form></details>;
}
