import { errorMessage } from '../errors';
import { tr } from '../translations';
import { useRef, useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { api, type Meeting } from '../api';
import type { Labels } from '../i18n';
import { Recorder } from './Recorder';
import { JobProgress } from './JobProgress';
import { MeetingDetails, CandidateHistory } from './MeetingDetails';

export function Workspace({id,t,back,role}: {id:string;t:Labels;back:()=>void;role:string}) {
 const [tab,setTab]=useState('review'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState(''),[selection,setSelection]=useState<any>(null),[field,setField]=useState('text');
 const [offset,setOffset]=useState(0);
 const clipEnd=useRef<number|null>(null);
 const [profile,setProfile]=useState({device:'cuda',parakeet:false,diarization:false});
 const capabilities=useQuery({queryKey:['proof'],queryFn:()=>api('/system/proof')});
 const player=useRef<HTMLAudioElement>(null),cache=useQueryClient();
 const meeting=useQuery({queryKey:['meeting',id],queryFn:()=>api<Meeting>(`/meetings/${id}`),refetchInterval:2000});
 const review=useQuery({queryKey:['review',id],queryFn:()=>api<any>(`/meetings/${id}/items`),refetchInterval:4000});
 const transcript=useQuery({queryKey:['transcript',id,search,offset],queryFn:()=>api<any[]>(`/meetings/${id}/transcript?q=${encodeURIComponent(search)}&limit=200&offset=${offset}`),refetchInterval:5000});
 const snapshots=useQuery({queryKey:['snapshots',id],queryFn:()=>api<any[]>(`/meetings/${id}/snapshots`)});
 const groups=useQuery({queryKey:['groups'],queryFn:()=>api<any[]>('/recipient-groups')});
 const refresh=async()=>{await cache.invalidateQueries();};
 async function act(fn:()=>Promise<unknown>){setError('');setBusy(true);try{await fn();await refresh();}catch(e){setError(e instanceof Error ? e.message : tr('The request failed. Check the form, refresh, and try again.'));}finally{setBusy(false);}}
 async function upload(file:File){const form=new FormData();form.append('file',file);await act(()=>api(`/meetings/${id}/uploads`,'POST',form));}
 function play(segment:any){const audio=player.current;if(!audio)return;const start=Math.max(0,segment.start/16000-2);clipEnd.current=segment.end/16000+2;audio.onloadedmetadata=()=>{audio.currentTime=start;void audio.play();};audio.src=`/api/v1/assets/${segment.asset_id}/audio`;audio.load();}
 async function playEvidence(ref:any){try{const segment=await api(`/segments/${ref.segment_id}`);play(segment);}catch(e){setError(e instanceof Error ? e.message : tr('The request failed. Check the form, refresh, and try again.'));}}

 if(meeting.isPending)return <p role="status">{t.loading}</p>;
 if(meeting.isError)return <p role="alert">{String(meeting.error)}</p>;
 const m=meeting.data,candidates=review.data?.candidates||[],selected=candidates.find((c:any)=>c.id===selection)||candidates[0];
 const refs=selected?.evidence?.filter((e:any)=>e.field===field)||[];
 return <><button className="textbutton" onClick={back}>← {t.back}</button><div className="pageheading"><div><p className="eyebrow">{tr(m.classification)} · {m.date||tr("Date unknown")}</p><h1>{m.title}</h1><p>{m.participants?.map(p=>p.name).join(' · ')||tr('No participants entered')}</p></div><span className="badge">{tr(m.status.replaceAll('_',' '))}</span></div>
 {error&&<p className="error" role="alert">{error}</p>}
 <MeetingDetails meeting={m} role={role} busy={busy} act={act} back={back}/>
 <details className="card" open={m.status!=='awaiting_review'}><summary>{tr("Audio & processing")}</summary><fieldset className="mutation-controls" disabled={role==='viewer'}><div className="toolbar"><label>{tr("Inference device")}<select value={profile.device} onChange={e=>setProfile({...profile,device:e.target.value})}><option value="cuda">{tr("GPU")}</option><option value="cpu">{tr("CPU (explicit slower profile)")}</option></select></label>{(['parakeet','diarization'] as const).map(name=><label key={name}><span><input type="checkbox" checked={profile[name]} disabled={!capabilities.data?.capabilities?.[name]?.available} onChange={e=>setProfile({...profile,[name]:e.target.checked})}/>{tr(name)}</span><small>{tr(capabilities.data?.capabilities?.[name]?.available?'Available, not qualified':'Assets or dependencies not prepared')}</small></label>)}</div><div className="toolbar"><label className="filelabel">{t.upload}<input aria-label={t.upload} type="file" accept=".wav,.mp3,.m4a,.ogg,.flac,.webm" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);}}/></label>{m.assets?.map(a=><span key={a.id}>{(a.samples/a.sample_rate).toFixed(1)}{tr(" s saved ")}<button disabled={busy} onClick={()=>act(()=>api(`/meetings/${id}/jobs`,'POST',{asset_id:a.id,...profile}))}>{t.process}</button></span>)}</div>{m.recordings?.filter(r=>r.state==='recording'&&r.acknowledged_chunks>0).map(r=><div className="notice" key={r.id}><strong>{tr("Recover saved recording")}</strong><p>{(r.acknowledged_samples/r.rate).toFixed(1)}{tr(" seconds acknowledged. Unacknowledged audio from a closed browser cannot be recovered.")}</p><button disabled={busy} onClick={()=>act(()=>api(`/recordings/${r.id}/finish`,'POST',{count:r.acknowledged_chunks,gaps:[{reason:'Recovered after interruption; missing wall interval unknown'}]}))}>{tr("Seal acknowledged audio")}</button></div>)}<Recorder meeting={id} t={t} done={refresh}/>{m.jobs?.map(j=><div className="job" role="status" key={j.id}><strong>{tr(j.stage.replaceAll('_',' '))}</strong> · {tr(j.state)}<JobProgress job={j}/>{j.error&&<span className="error">{errorMessage(j.error)}{tr(" — source audio retained")}</span>}{['queued','running'].includes(j.state)?<button className="secondary" onClick={()=>act(()=>api(`/jobs/${j.id}/cancel`,'POST'))}>{tr("Cancel analysis")}</button>:['failed','cancelled'].includes(j.state)?<button onClick={()=>act(()=>api(`/jobs/${j.id}/retry`,'POST'))}>{tr("Retry")}</button>:null}</div>)}</fieldset></details>
 <div className="tabs" role="tablist">{(['review','transcript','minutes'] as const).map(k=><button role="tab" aria-selected={tab===k} key={k} onClick={()=>setTab(k)}>{t[k]}</button>)}</div>
 {tab==='review'&&<div className="reviewgrid"><section className="card itemlist"><h2>{tr("Review queue ")}<span className="badge">{candidates.filter((c:any)=>!['accepted','excluded'].includes(c.review)).length}</span></h2>{!candidates.length&&<p>{tr("No extracted events yet. Process saved audio to begin.")}</p>}{candidates.map((c:any)=><button className={selected?.id===c.id?'selected':''} key={c.id} onClick={()=>{setSelection(c.id);setField('text');}}><strong>{c.body.subject}</strong><small>{tr(c.body.kind)} · {tr(c.review.replaceAll('_',' '))}</small></button>)}</section>
 <section className="card detail">{selected?<><p className="eyebrow">{tr(selected.body.category)} · {tr(selected.body.kind)}</p><h2>{selected.body.text}</h2><p className="badge">{tr("Review: ")}{tr(selected.review.replaceAll('_',' '))}</p>{(['owner','due','condition','value'] as const).map(f=><button className="field" key={f} onClick={()=>setField(f)}><span>{tr(f)}</span><strong>{selected.body[f]||t.notSpecified}</strong><small>{tr("View source ↗")}</small></button>)}{selected.body.uncertainties.length>0&&<p className="caption">{tr("Processing warning (original wording)")}</p>}{selected.body.uncertainties.map((u:string)=><p className="notice" key={u}>{u}</p>)}<div className="toolbar"><button disabled={busy||role==='viewer'||selected.review==='accepted'} onClick={()=>act(()=>api(`/review-issues/${selected.id}/resolve`,'POST',{revision:review.data.revision,action:'accepted'}))}>{t.accept}</button><button className="secondary" disabled={busy||role==='viewer'||selected.review==='excluded'} onClick={()=>act(()=>api(`/review-issues/${selected.id}/resolve`,'POST',{revision:review.data.revision,action:'excluded'}))}>{t.exclude}</button></div><p className="caption">{tr("Acceptance confirms your review of the interpretation, including each field.")}</p>{role!=='viewer'&&<CorrectionForm key={selected.id} candidate={selected} revision={review.data.revision} act={act} corrected={setSelection} subjects={[...new Set<string>(candidates.map((c:any)=>c.body.subject))]}/> }</>:<h2>{tr("Review the evidence before approving")}</h2>}</section>
 <aside className="card evidence"><p className="eyebrow">{tr("SOURCE EVIDENCE · ")}{tr(field)}</p>{refs.length?refs.map((r:any)=>{return <div key={r.id}><blockquote>{r.quote}</blockquote><p>{tr("Transcript revision ")}{r.revision}</p><button className="secondary" onClick={()=>playEvidence(r)}>{tr("▶ Play source clip")}</button></div>;}):<p>{tr("No source supplied for this field. Keep unsupported values unresolved.")}</p>}<CandidateHistory id={selected?.id}/></aside></div>}
 {tab==='transcript'&&<section className="card"><label>{t.search}<input value={search} onChange={e=>{setSearch(e.target.value);setOffset(0);}} placeholder={tr("Search original speech…")}/></label><p className="caption">{tr("Original source language · 200 segments per page · corrections preserve history")}</p>{transcript.data?.map(s=><TranscriptRow readOnly={role==='viewer'} key={s.id} segment={s} play={()=>play(s)} save={(text,speaker)=>act(()=>api(`/segments/${s.id}/revisions`,'POST',{revision:s.revision,text,speaker}))}/>)}<div className="toolbar"><button className="secondary" disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-200))}>{tr("Previous segments")}</button><span>{offset+1}–{offset+(transcript.data?.length||0)}</span><button className="secondary" disabled={(transcript.data?.length||0)<200} onClick={()=>setOffset(offset+200)}>{tr("Next segments")}</button></div>{transcript.data?.length===0&&<p>{tr("No transcript available.")}</p>}</section>}
 {tab==='minutes'&&<section className="card"><div className="pageheading"><div><h2>{tr("Versioned minutes")}</h2><p>{tr("Resolve every review item, then create an immutable preview.")}</p></div><button disabled={busy||role==='viewer'} onClick={()=>act(()=>api(`/meetings/${id}/snapshots`,'POST',{revision:m.revision}))}>{tr("Create preview")}</button></div>{snapshots.data?.map(s=><Snapshot key={s.id} snapshot={s} revision={m.revision} t={t} groups={groups.data||[]} act={act} busy={busy||role==='viewer'}/>)}{!snapshots.data?.length&&<p>{tr("No versions yet. Approval and sending are separate steps.")}</p>}</section>}
 <div className="player"><span>{tr("Source audio")}</span><audio ref={player} controls onTimeUpdate={()=>{if(player.current&&clipEnd.current!==null&&player.current.currentTime>=clipEnd.current){player.current.pause();clipEnd.current=null;}}} preload="none" src={m.assets?.[0]?`/api/v1/assets/${m.assets[0].id}/audio`:undefined}/><span className="caption">{tr("Original speech is retained")}</span></div></>;
}

function TranscriptRow({segment:s,play,save,readOnly}:{readOnly:boolean;segment:any;play:()=>void;save:(text:string,speaker:string|null)=>void}) {
 const [editing,setEditing]=useState(false),[text,setText]=useState(s.text),[speaker,setSpeaker]=useState(s.speaker||'');
 return <article className="segment"><button className="timestamp" onClick={play}>▶ {(s.start/16000).toFixed(1)}s</button><div>{editing?<><textarea value={text} onChange={e=>setText(e.target.value)}/><label>{tr("Speaker (manual)")}<input value={speaker} onChange={e=>setSpeaker(e.target.value)}/></label><button onClick={()=>{save(text,speaker||null);setEditing(false);}}>{tr("Save correction")}</button></>:<><small>{s.speaker||tr('Unknown speaker')}{tr(" · revision ")}{s.revision}</small><p>{s.text}</p>{JSON.parse(s.alternatives||'[]').map((a:any,i:number)=><details key={i}><summary>{tr("Alternative hypothesis · ")}{a.engine}</summary><p>{a.text}</p><p className="notice">{tr("Separate recognizer output; never merged into the source transcript.")}</p></details>)}{!readOnly&&<button className="textbutton" onClick={()=>setEditing(true)}>{tr("Correct transcript / speaker")}</button>}</>}</div></article>;
}

function Snapshot({snapshot:s,revision,t,groups,act,busy}:{snapshot:any;revision:number;t:Labels;groups:any[];act:(fn:()=>Promise<unknown>)=>void;busy:boolean}) {
 const delivery=useQuery({queryKey:['delivery',s.id],queryFn:()=>api<any[]>(`/snapshots/${s.id}/deliveries`),refetchInterval:2000});
 const [groupId,setGroupId]=useState(''),[allowOlder,setAllowOlder]=useState(false);
 const group=groups.find(g=>g.id===groupId)||groups.find(g=>g.id===s.suggested_group_id)||groups[0],stale=s.revision!==revision;
 return <article className="snapshot"><h3>{tr("Revision ")}{s.revision} <span className="badge">{tr(s.approved?'Approved':'Draft')}{stale?' · '+tr('Older version'):''}</span></h3><p>{tr("Template version")}: {s.template_revision??0}</p><p className="hash">SHA-256 {s.hash}</p><div className="toolbar">{['html','pdf','json'].map(f=><a key={f} target="_blank" rel="noreferrer" href={`/api/v1/snapshots/${s.id}/exports/${f}`}>{f.toUpperCase()} ↗</a>)}</div><label>{tr("Recipient group")}<select aria-label={tr("Recipient group")} value={group?.id||''} onChange={e=>setGroupId(e.target.value)}>{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label><p>{tr("Allowed recipients: ")}<strong>{group?.addresses.join(', ')||tr('No group configured')}</strong>{tr(" · group version ")}{group?.version}</p><div className="toolbar"><button disabled={busy||!!s.approved||stale} onClick={()=>act(()=>api(`/snapshots/${s.id}/approve`,'POST',{revision}))}>{t.approve}</button><button disabled={busy||!s.approved||(stale&&!allowOlder)||!group} onClick={()=>act(()=>api(`/snapshots/${s.id}/deliveries`,'POST',{group_id:group.id,group_version:group.version,explicitly_send_older:stale&&allowOlder}))}>{stale?tr("Send this older approved version"):t.send}</button></div>{stale&&s.approved&&<label><input type="checkbox" checked={allowOlder} onChange={e=>setAllowOlder(e.target.checked)}/>{tr("I choose this older approved version and the recipients shown above.")}</label>}{stale&&<p className="notice">{tr("This version is retained for history. Create a current preview to send.")}</p>}{delivery.data?.map(d=><div key={d.id}><p role="status">{tr("Local delivery: ")}{tr(d.state.replaceAll('_',' '))} {d.error?errorMessage(d.error):''}</p><p className="caption">{tr("Recipients for this delivery")}: {JSON.parse(d.addresses).join(', ')}</p>{d.state==='failed'&&<button disabled={busy||(stale&&!allowOlder)} onClick={()=>act(()=>api(`/deliveries/${d.id}/retry`,'POST',{explicitly_send_older:stale&&allowOlder}))}>{tr('Retry this failed delivery')}</button>}{d.state==='uncertain'&&<p className="notice">{tr('Delivery is uncertain. Check the mail server; this attempt cannot be retried automatically.')}</p>}</div>)}</article>;
}

function CorrectionForm({candidate,revision,act,corrected,subjects}:{candidate:any;revision:number;act:(fn:()=>Promise<unknown>)=>void;corrected:(id:string)=>void;subjects:string[]}) {
 return <details><summary>{tr("Secretary amendment")}</summary><p className="notice">{tr("Changes are labeled as reviewer additions. No audio evidence is invented for edited fields.")}</p><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);act(async()=>{const result=await api(`/items/${candidate.id}/corrections`,'POST',{revision,subject:f.get('subject'),text:f.get('text'),owner:f.get('owner')||null,due:f.get('due')||null,condition:f.get('condition')||null,value:f.get('value')||null,resolved_issues:f.getAll('resolved_issues'),reason:f.get('reason'),category:f.get('category'),kind:f.get('kind')});corrected(result.id);});}}><label>{tr("Topic / item key")}<input name="subject" list="known-topics" defaultValue={candidate.body.subject} required maxLength={160}/></label><datalist id="known-topics">{subjects.map(subject=><option key={subject} value={subject}/>)}</datalist><p className="caption">{tr("Use the same key only for the same task and scope. A new key separates unrelated items. Explain the link or split below.")}</p><label>{tr("Text")}<textarea name="text" aria-label={tr("Text")} defaultValue={candidate.body.text} required/></label><label>{tr("Owner")}<input name="owner" defaultValue={candidate.body.owner||''}/></label><label>{tr("Due")}<input name="due" type="date" defaultValue={candidate.body.due||''}/></label><label>{tr("Condition")}<textarea name="condition" aria-label={tr("Condition")} defaultValue={candidate.body.condition||''}/></label><label>{tr("Value")}<input name="value" defaultValue={candidate.body.value||''}/></label><label>{tr("Category")}<select name="category" defaultValue={candidate.body.category}>{['action','decision','information'].map(v=><option key={v} value={v}>{tr(v)}</option>)}</select></label><label>{tr("Speech act")}<select name="kind" defaultValue={candidate.body.kind}>{['propose','confirm','amend','reject','cancel','reopen','inform'].map(v=><option key={v} value={v}>{tr(v)}</option>)}</select></label>{candidate.body.uncertainties.length>0&&<fieldset><legend>{tr("Issues I have resolved")}</legend><p className="caption">{tr("Only check an issue after reviewing its source. Your reason is retained in the amendment history.")}</p>{candidate.body.uncertainties.map((issue:string)=><label key={issue}><input type="checkbox" name="resolved_issues" value={issue}/>{issue}</label>)}</fieldset>}<label>{tr("Reason for amendment")}<input name="reason" required minLength={3}/></label><button>{tr("Save reviewed amendment")}</button></form></details>;
}
